### ISSUE TITLE
NullPointerException due to _loginCallback being set to null

### ISSUE THREAD

**Issue by fschrofner** [oracle/cordova-plugin-oracle-idm-auth#2]
In our case the whole application crashes, when the authentication fails.
This apparently happens because `_loginCallback` is set to null inside `onAuthenticationCompleted`, while `onAuthenticationChallenge`is called again to populate the fields. Inside the `USERNAME_PWD_REQUIRED` case, it then tries to call the `success` method on the null object, causing the crash.

#### Relevant Code 
```java
case USERNAME_PWD_REQUIRED:
        OMLog.debug(TAG, "Handling username password challenge.");
        Map<String, Object> fieldsMap = new HashMap<String, Object>();
        fieldsMap.put("challengeFields", fields);

        if (errorCode != null) {
          OMLog.debug(TAG, "Setting error code: " + errorCode);
          fields.put(_CHALLENGE_ERROR, IdmAuthenticationPlugin.errorToMap(errorCode));
        }
        
        _loginCallback.success(new JSONObject(fieldsMap)); //crash happens here
```

#### Logcat
```
D/IDMMobileSDK: [IdmAuthenticationFactory] Creating new Authentication flow.
D/IDMMobileSDK: [IdmAuthentication] Converting JSON to auth map.
D/IDMMobileSDK: [IdmAuthentication] Setting up OMMSS instance with: {AuthServerType=OAuth20, OAuthAuthorizationGrantType=OAuthAuthorizationCode, OAMOAuthServiceEndpoint=https://example.com/ms_oauth/oauth2/endpoints/oauthservice, OAuthScope=[all], ApplicationName=ExampleApp, OAuthClientID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, OAuthAuthorizationEndpoint=https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize, BrowserMode=Embedded, OAuthRedirectEndpoint=https://example.com/kerberos/printenv.pl, OAuthTokenEndpoint=https://example.com/ms_oauth/oauth2/endpoints/oauthservice/token}
D/IDMMobileSDK: [oracle.idm.mobile.configuration.OMOAuthMobileSecurityConfiguration] Grant type = Authorization_code. PKCE Enabled = false
I/IDMMobileSDK: [oracle.idm.mobile.configuration.OMOAuthMobileSecurityConfiguration] Additional Initialization required
D/IDMMobileSDK: [OMMobileSecurityService] setup
V/IDMMobileSDK: [OMConnectionHandler] httpGet URL              : https://example.com/ms_oauth/oauth2/endpoints/oauthservice/appprofiles/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?device_os=Android_REL&os_ver=6.0.1
I/IDMMobileSDK: [OMConnectionHandler] is authentication mode    : false
I/IDMMobileSDK: [OMConnectionHandler] Response headers required : true
I/IDMMobileSDK: [OMConnectionHandler] Response code required    : true
I/IDMMobileSDK: [OMConnectionHandler] Response string required  : true
D/IDMMobileSDK: [OMSSLSocketFactory] Creating SSLSocketFactory for protocol: TLS Client Certificate support : false
I/IDMMobileSDK: [OMConnectionHandler] Added the custom headers to the client
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
V/IDMMobileSDK: [OMCookieManager] INSIDE get
D/IDMMobileSDK: [OMCookieManager] REQUEST Headers:
I/IDMMobileSDK: [OMConnectionHandler] Hostname: example.com verified
V/IDMMobileSDK: [OMCookieManager] INSIDE put
D/IDMMobileSDK: [OMCookieManager] RESPONSE Headers:
V/IDMMobileSDK: [OMConnectionHandler] response code before processing : 200
V/IDMMobileSDK: [OMConnectionHandler] response code after processing : 200
V/IDMMobileSDK: [OMCookieManager] INSIDE put
D/IDMMobileSDK: [OMCookieManager] RESPONSE Headers:
I/IDMMobileSDK: [OMConnectionHandler] disconnecting...
D/oracle.idm.mobile.configuration.OMMSOAuthMobileSecurityConfiguration:  downloadClientServiceProfile OAuth Client service profile  is {"allowedGrantTypes":["code","authorization_code","password","oracle-idm:/oauth/grant-type/challenge-answer"],"client_id":"ExampleApp","mobileAppConfig":{"claimAttributes":["oracle:idm:claims:client:sdkversion","oracle:idm:claims:client:networktype","oracle:idm:claims:client:fingerprint","oracle:idm:claims:client:phonenumber","oracle:idm:claims:client:ostype","oracle:idm:claims:client:imei","oracle:idm:claims:client:phonecarriername","oracle:idm:claims:client:udid","oracle:idm:claims:client:geolocation","oracle:idm:claims:client:vpnenabled","oracle:idm:claims:client:macaddress","oracle:idm:claims:client:deviceid","oracle:idm:claims:client:locale","oracle:idm:claims:client:osversion","oracle:idm:claims:client:containerid"]},"oauthAuthZService":"/ms_oauth/oauth2/endpoints/oauthservice/authorize","oauthNotificationService":"/ms_oauth/oauth2/endpoints/oauthservice/push","oauthTokenService":"/ms_oauth/oauth2/endpoints/oauthservice/tokens","oracleConsentServiceProtection":"OAM","oracleMobileSecurityLevel":"LOW","server_side_sso":false,"sharedKeyAttributeName":"secret_key","userConsentService":["/ms_oauth/resources/consentmanagement"],"userProfileService":["/ms_oauth/resources/userprofile"]}
D/IDMMobileSDK: [IdmAuthentication] Setup completed.
D/IDMMobileSDK: [IdmAuthentication] Exit Setup completed..
D/IDMMobileSDK: [IdmAuthenticationPlugin] Validating arguments.
D/IDMMobileSDK: [IdmAuthentication] Adding timeout callback.
D/IDMMobileSDK: [IdmAuthenticationPlugin] Validating arguments.
D/IDMMobileSDK: [IdmAuthentication] isAuthenticated invoked.
I/IDMMobileSDK: [AuthenticationServiceManager] initialize
I/IDMMobileSDK: [AuthenticationServiceManager] initAuthServiceHandlers
D/IDMMobileSDK: [AuthenticationServiceManager]  Authentication context for the key ExampleApp retrieved from the credential store is  : null
D/IDMMobileSDK: [IdmAuthenticationPlugin] Validating arguments.
D/IDMMobileSDK: [IdmAuthentication] Start login process.
D/IDMMobileSDK: [OMMobileSecurityService] Authenticate API called for first time after app launch -> Removing session cookies
D/IDMMobileSDK: [OMCookieManager] Removed session cookies
D/IDMMobileSDK: [OAuthConnectionsUtil] OAuthConnection Utils -> Use PKCE : false
D/IDMMobileSDK: [OAuthConnectionsUtil] OAuthConnection Utils -> Register Client : false
I/IDMMobileSDK: [AuthenticationServiceManager] startAuthenticationProcess
D/IDMMobileSDK: [AuthenticationServiceManager]  Authentication context for the key ExampleApp retrieved from the credential store is  : null
I/IDMMobileSDK: [OAuthAuthorizationCodeLogoutHandler] initialized OAuthAuthZCodeLogoutHandler: EMBEDDED
V/IDMMobileSDK: [OAuthAuthorizationCodeService] initialized
I/IDMMobileSDK: [DefaultStateTransition] getInitialState authScheme : OAUTH20 TYPE : OAUTH20_AC_SERVICE
I/IDMMobileSDK: [OMMobileSecurityService] Resetting connection handler
I/IDMMobileSDK: [AuthenticationServiceManager] processAuthRequest
V/IDMMobileSDK: [OAuthAuthorizationCodeService] collectChallengeInput
I/IDMMobileSDK: [OAuthAuthorizationCodeService] Creating Challenge for browser mode: EMBEDDED
I/IDMMobileSDK: [OAuthAuthorizationCodeService] Challenge : type : EMBEDDED_WEBVIEW_REQUIRED
D/IDMMobileSDK: [IdmAuthentication] onAuthenticationChallenge invoked.
D/IDMMobileSDK: [IdmAuthentication] Handling embedded webview challenge.
D/IDMMobileSDK: [IdmAuthentication] Launching webview activity
D/IDMMobileSDK: [WebViewActivity] Enabling cancel button for LOGIN challenge.
I/IDMMobileSDK: [OAuthAuthorizationCodeCompletionHandler] proceed
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] configureView
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] Redirect EP: https://example.com/kerberos/printenv.pl
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] Loading login load  URL in the webview https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&state=474156&scope=all&
D/IDMMobileSDK: [WebViewActivity] Created webview activity and passed on to IDM SDK.
V/IDMMobileSDK: [BaseWebViewClient] shouldInterceptRequest
V/IDMMobileSDK: [BaseWebViewClient] shouldInterceptRequest: url = https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&state=474156&scope=all&
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] onPageStarted: https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&state=474156&scope=all&
V/IDMMobileSDK: [BaseWebViewClient] onPageStarted: url = https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&state=474156&scope=all&
V/IDMMobileSDK: [BaseWebViewClient] onLoadResource: url = https://example.com/ms_oauth/oauth2/endpoints/oauthservice/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&state=474156&scope=all&
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] shouldOverrideUrlLoading: https://example.com/ms_oauth/oauth2/ui/oauthservice/showconsent?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&scope=all&state=474156&oracle_client_name=ExampleApp
V/IDMMobileSDK: [BaseWebViewClient] shouldOverrideUrlLoading: url = https://example.com/ms_oauth/oauth2/ui/oauthservice/showconsent?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&scope=all&state=474156&oracle_client_name=ExampleApp
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] onPageStarted: https://example.com/ms_oauth/oauth2/ui/oauthservice/showconsent?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&scope=all&state=474156&oracle_client_name=ExampleApp
V/IDMMobileSDK: [BaseWebViewClient] onPageStarted: url = https://example.com/ms_oauth/oauth2/ui/oauthservice/showconsent?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fexample.com%2Fkerberos%2Fprintenv.pl&scope=all&state=474156&oracle_client_name=ExampleApp
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] shouldOverrideUrlLoading: https://example.com/kerberos/printenv.pl?error=server_error&state=474156
D/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] Response from OAuth Server to redirect URL: https://example.com/kerberos/printenv.pl?error=server_error&state=474156
I/IDMMobileSDK: [ASMInputControllerImpl] onInputsAvailable 
I/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask] doInBackground authService: OAUTH20_AC_SERVICE
I/IDMMobileSDK: [OAuthAuthorizationCodeService] handleAuthentication
E/IDMMobileSDK: [OAuthAuthenticationService] Error Response from Server -> error: server_error error_description: null
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] onPageStarted: https://example.com/kerberos/printenv.pl?error=server_error&state=474156
V/IDMMobileSDK: [BaseWebViewClient] onPageStarted: url = https://example.com/kerberos/printenv.pl?error=server_error&state=474156
I/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask] onPostExecute
D/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask] Authentication context status : FAILURE
D/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask] No exception raised in background thread
I/IDMMobileSDK: [IDMMobileSDK] [DefaultStateTransition] doStateTransition FAILURE
D/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask_onPostExecute] Authentication service is 
D/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask_onPostExecute] Authentication context status is FAILURE
E/IDMMobileSDK: [AuthenticationServiceManager.AuthenticationAsyncTask] Authentication Context Status : FAILURE and does require app input? false
D/IDMMobileSDK: [AuthenticationServiceManager] [sendFailureAfterRetry] Failure count is 0
D/IDMMobileSDK: [AuthenticationServiceManager_setAuthenticationContext] Cleared in-memory authContext
I/IDMMobileSDK: [AuthenticationServiceManager] No completion handler impl for type: OAUTH_MS_DYCR
D/IDMMobileSDK: [OMAuthenticationContext_deleteAuthContext] Logout authService: null
E/IDMMobileSDK: [AuthenticationServiceManager] sendFailure -> errorCode : 40233 errorMessage: server_error: The authorization server encountered an unexpected condition that prevented it from fulfilling the request.
D/IDMMobileSDK: [IdmAuthentication] onAuthenticationCompleted invoked.
D/IDMMobileSDK: [IdmAuthentication] Hide webview after successful authentication or logout.
E/IDMMobileSDK: [IdmAuthentication] Error in authentication completed: server_error: The authorization server encountered an unexpected condition that prevented it from fulfilling the request.
D/IDMMobileSDK: [WebViewActivity] Finishing the activity.
D/IDMMobileSDK: [WebViewActivity] Destroyed webview activity.
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] shouldOverrideUrlLoading: https://example.com/oam/server/obrareq.cgi?encquery%3Du2m0G4Uk5lE3yWAw9%2FMHt32PYGjGwR%2FovaJ3Om8mvqlLWqMn5dNtWVE3XcdnOpADR6UEFiu6jEa2vmiRRD8xTz%2BFxgDrUKRslksPZheFHg1bNcfxCfa6bi7zugc2osDPxRjmME8%2BbwaJ%2FqymjA66q%2FlnxYO9wlpx8lI%2Bo6PEH4nm79Qxv9xY6zPkakhzT2lu1QZJPyF4TFQUzQKO9Ic8WFY1Oz%2FxznNG8iGzVYf9ggRo%2BbHYn2s63rR7AwABFwx78uMBcZIyli3w7IDCRdU6AzE9R8SipGXl2aQf%2Bow2gB2c8ttgyottiNSAWSLVffs%2FSZWmEp%2BzjV%2FbJvVzB9yNrLaXOKxtK3uVCrLE8kIb82YuJtFgKxHaKiQpFh%2BMO1K1FyRoberqmbhsCVN5yBuJ68NgAAUljvAC7Lnlo1CLLx3kEA%2Be9XrX%2FtOHI9aX%2BhcU%20agentid%3DWG_COLLABORATION_A%20ver%3D1%20crmethod%3D2&ECID-Context=1.005OWGhhdn64mnK5uVt1iX000ADd000U37%3BkXjE
V/IDMMobileSDK: [BaseWebViewClient] shouldOverrideUrlLoading: url = https://example.com/oam/server/obrareq.cgi?encquery%3Du2m0G4Uk5lE3yWAw9%2FMHt32PYGjGwR%2FovaJ3Om8mvqlLWqMn5dNtWVE3XcdnOpADR6UEFiu6jEa2vmiRRD8xTz%2BFxgDrUKRslksPZheFHg1bNcfxCfa6bi7zugc2osDPxRjmME8%2BbwaJ%2FqymjA66q%2FlnxYO9wlpx8lI%2Bo6PEH4nm79Qxv9xY6zPkakhzT2lu1QZJPyF4TFQUzQKO9Ic8WFY1Oz%2FxznNG8iGzVYf9ggRo%2BbHYn2s63rR7AwABFwx78uMBcZIyli3w7IDCRdU6AzE9R8SipGXl2aQf%2Bow2gB2c8ttgyottiNSAWSLVffs%2FSZWmEp%2BzjV%2FbJvVzB9yNrLaXOKxtK3uVCrLE8kIb82YuJtFgKxHaKiQpFh%2BMO1K1FyRoberqmbhsCVN5yBuJ68NgAAUljvAC7Lnlo1CLLx3kEA%2Be9XrX%2FtOHI9aX%2BhcU%20agentid%3DWG_COLLABORATION_A%20ver%3D1%20crmethod%3D2&ECID-Context=1.005OWGhhdn64mnK5uVt1iX000ADd000U37%3BkXjE
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] onPageStarted: https://example.com/oam/server/obrareq.cgi?encquery%3Du2m0G4Uk5lE3yWAw9%2FMHt32PYGjGwR%2FovaJ3Om8mvqlLWqMn5dNtWVE3XcdnOpADR6UEFiu6jEa2vmiRRD8xTz%2BFxgDrUKRslksPZheFHg1bNcfxCfa6bi7zugc2osDPxRjmME8%2BbwaJ%2FqymjA66q%2FlnxYO9wlpx8lI%2Bo6PEH4nm79Qxv9xY6zPkakhzT2lu1QZJPyF4TFQUzQKO9Ic8WFY1Oz%2FxznNG8iGzVYf9ggRo%2BbHYn2s63rR7AwABFwx78uMBcZIyli3w7IDCRdU6AzE9R8SipGXl2aQf%2Bow2gB2c8ttgyottiNSAWSLVffs%2FSZWmEp%2BzjV%2FbJvVzB9yNrLaXOKxtK3uVCrLE8kIb82YuJtFgKxHaKiQpFh%2BMO1K1FyRoberqmbhsCVN5yBuJ68NgAAUljvAC7Lnlo1CLLx3kEA%2Be9XrX%2FtOHI9aX%2BhcU%20agentid%3DWG_COLLABORATION_A%20ver%3D1%20crmethod%3D2&ECID-Context=1.005OWGhhdn64mnK5uVt1iX000ADd000U37%3BkXjE
V/IDMMobileSDK: [BaseWebViewClient] onPageStarted: url = https://example.com/oam/server/obrareq.cgi?encquery%3Du2m0G4Uk5lE3yWAw9%2FMHt32PYGjGwR%2FovaJ3Om8mvqlLWqMn5dNtWVE3XcdnOpADR6UEFiu6jEa2vmiRRD8xTz%2BFxgDrUKRslksPZheFHg1bNcfxCfa6bi7zugc2osDPxRjmME8%2BbwaJ%2FqymjA66q%2FlnxYO9wlpx8lI%2Bo6PEH4nm79Qxv9xY6zPkakhzT2lu1QZJPyF4TFQUzQKO9Ic8WFY1Oz%2FxznNG8iGzVYf9ggRo%2BbHYn2s63rR7AwABFwx78uMBcZIyli3w7IDCRdU6AzE9R8SipGXl2aQf%2Bow2gB2c8ttgyottiNSAWSLVffs%2FSZWmEp%2BzjV%2FbJvVzB9yNrLaXOKxtK3uVCrLE8kIb82YuJtFgKxHaKiQpFh%2BMO1K1FyRoberqmbhsCVN5yBuJ68NgAAUljvAC7Lnlo1CLLx3kEA%2Be9XrX%2FtOHI9aX%2BhcU%20agentid%3DWG_COLLABORATION_A%20ver%3D1%20crmethod%3D2&ECID-Context=1.005OWGhhdn64mnK5uVt1iX000ADd000U37%3BkXjE
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] shouldOverrideUrlLoading: https://example.com/oam/CredCollectServlet/WNA?bmctx=A432872F664F000D474D141582E2381F8A0B922B08C3AD7C7F4986999B3E95C3&spnegotoken=string&challenge_url=%2Foam%2FCredCollectServlet%2FWNA&request_id=164454554938531376&authn_try_count=0&locale=de_AT&resource_url=http%253A%252F%252Fexample.com%252Fkerberos%252Fprintenv.pl%253Ferror%253Dserver_error%2526state%253D474156
V/IDMMobileSDK: [BaseWebViewClient] shouldOverrideUrlLoading: url = https://example.com/oam/CredCollectServlet/WNA?bmctx=A432872F664F000D474D141582E2381F8A0B922B08C3AD7C7F4986999B3E95C3&spnegotoken=string&challenge_url=%2Foam%2FCredCollectServlet%2FWNA&request_id=164454554938531376&authn_try_count=0&locale=de_AT&resource_url=http%253A%252F%252Fexample.com%252Fkerberos%252Fprintenv.pl%253Ferror%253Dserver_error%2526state%253D474156
I/IDMMobileSDK: [oracle.idm.mobile.auth.webview.OAuthWebViewConfigurationHandler] onPageStarted: https://example.com/oam/CredCollectServlet/WNA?bmctx=A432872F664F000D474D141582E2381F8A0B922B08C3AD7C7F4986999B3E95C3&spnegotoken=string&challenge_url=%2Foam%2FCredCollectServlet%2FWNA&request_id=164454554938531376&authn_try_count=0&locale=de_AT&resource_url=http%253A%252F%252Fexample.com%252Fkerberos%252Fprintenv.pl%253Ferror%253Dserver_error%2526state%253D474156
V/IDMMobileSDK: [BaseWebViewClient] onPageStarted: url = https://example.com/oam/CredCollectServlet/WNA?bmctx=A432872F664F000D474D141582E2381F8A0B922B08C3AD7C7F4986999B3E95C3&spnegotoken=string&challenge_url=%2Foam%2FCredCollectServlet%2FWNA&request_id=164454554938531376&authn_try_count=0&locale=de_AT&resource_url=http%253A%252F%252Fexample.com%252Fkerberos%252Fprintenv.pl%253Ferror%253Dserver_error%2526state%253D474156
D/IDMMobileSDK: [LoginWebViewHandler_onReceivedHttpAuthRequest] host = example.com realm = OAM 11g
I/IDMMobileSDK: [AuthenticationService] basicAuthChallenge : type : USERNAME_PWD_REQUIRED,{"password_key":null,"http_auth_host_key":"example.com","username_key":null,"http_auth_realm_key":"OAM 11g"}
V/IDMMobileSDK: [BasicAuthCompletionHandler]  createChallengeRequest
D/IDMMobileSDK: [IdmAuthentication] onAuthenticationChallenge invoked.
D/IDMMobileSDK: [IdmAuthentication] Handling username password challenge.
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null object reference
W/System.err:     at oracle.idm.auth.plugin.IdmAuthentication.onAuthenticationChallenge(IdmAuthentication.java:409)
W/System.err:     at oracle.idm.mobile.auth.BasicAuthCompletionHandler.createChallengeRequest(BasicAuthCompletionHandler.java:61)
W/System.err:     at oracle.idm.mobile.auth.AuthenticationService.onReceivedHttpAuthRequest(AuthenticationService.java:191)
W/System.err:     at oracle.idm.mobile.auth.webview.LoginWebViewHandler$LoginWebViewClient.onReceivedHttpAuthRequest(LoginWebViewHandler.java:190)
W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedHttpAuthRequest(WebViewContentsClientAdapter.java:443)
W/System.err:     at org.chromium.android_webview.AwContents.onReceivedHttpAuthRequest(AwContents.java:722)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:158)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7229)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by anandvnath** [comment]
Once onAuthenticationCompleted is called the authentication is completed. So the question is why is onAuthenticationChallenge getting called after this? What is the flow in the app exactly?

**Comment by fschrofner** [comment]
As we're using a different configuration now, we do not run into this issue any more. Therefore I'm closing it.
